##
## EPITECH PROJECT, 2022
## ai
## File description:
## Makefile
##

SRC = zappy_ai

all: COMPIL

COMPIL:
	@cp src/main.py ./$(SRC) && chmod +x $(SRC)

clean:
	rm -f $(SRC)

fclean: clean

re: fclean all

.PHONY: all clean fclean re COMPIL .FORCE